# Generated by Django 3.2.8 on 2021-12-04 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_rename_karma_object_memecommentkarma_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memecommentkarma',
            old_name='date_created',
            new_name='date_added',
        ),
    ]
