# Generated by Django 3.2.8 on 2021-12-04 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_rename_date_created_memecommentkarma_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memecomment',
            old_name='date_added',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='memecommentkarma',
            old_name='date_added',
            new_name='date_created',
        ),
    ]
