# Generated by Django 3.2.10 on 2021-12-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20211204_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='memecommentkarma',
            name='value',
            field=models.IntegerField(default=1),
        ),
    ]
