# Generated by Django 3.2.10 on 2021-12-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20211231_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memecommentkarma',
            name='positive',
        ),
        migrations.AddField(
            model_name='memecomment',
            name='karma',
            field=models.IntegerField(blank=True, default=0, verbose_name='Karma points'),
        ),
    ]
