# Generated by Django 3.2.10 on 2021-12-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_auto_20211231_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='memecommentkarma',
            name='positive',
            field=models.BooleanField(default=True, verbose_name='Positive Comment'),
        ),
    ]
