# Generated by Django 3.2.12 on 2022-02-14 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_rename_sender_memecommentkarma_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memecomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.memecomment'),
        ),
    ]
