# Generated by Django 3.2.8 on 2021-10-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Superuser'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='karma',
            field=models.IntegerField(default=0, verbose_name='Karma points'),
        ),
    ]
