# Generated by Django 3.2.8 on 2021-10-19 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211017_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karma',
            name='created',
        ),
        migrations.AddField(
            model_name='karma',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
