# Generated by Django 3.2.8 on 2021-10-20 17:55

from django.db import migrations, models
import memes_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('karma', models.IntegerField(default=0)),
                ('hidden', models.BooleanField(blank=True, default=False)),
                ('accepted', models.BooleanField(blank=True, default=False)),
                ('data_accepted', models.DateTimeField(blank=True, null=True)),
                ('original_image', models.ImageField(max_length=255, upload_to=memes_app.models.upload_meme_original)),
            ],
        ),
    ]
