# Generated by Django 3.2.8 on 2021-10-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes_app', '0004_alter_meme_op'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='title_slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
