# Generated by Django 3.2.8 on 2021-10-22 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes_app', '0005_meme_title_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='title_slug',
        ),
    ]
