# Generated by Django 3.2.8 on 2021-10-23 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes_app', '0006_remove_meme_title_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meme',
            old_name='OP',
            new_name='original_poster',
        ),
    ]
