# Generated by Django 3.2.8 on 2021-11-11 21:56

import django.core.validators
from django.db import migrations, models
import memes_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('memes_app', '0009_meme_normal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='original_image',
            field=models.ImageField(max_length=255, upload_to=memes_app.models.upload_meme_original, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'gif'])]),
        ),
    ]
