# Generated by Django 3.2.8 on 2021-11-11 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes_app', '0010_alter_meme_original_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meme',
            old_name='data_accepted',
            new_name='date_accepted',
        ),
    ]
