# Generated by Django 3.2.8 on 2021-11-23 17:07

from django.db import migrations, models
import memes_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('memes_app', '0011_rename_data_accepted_meme_date_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='original_image',
            field=models.ImageField(max_length=255, upload_to=memes_app.models.upload_meme_original),
        ),
    ]
