# Generated by Django 3.2.10 on 2022-01-02 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memes_app', '0012_alter_meme_original_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='meme',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memes_app.category'),
        ),
    ]
