# Generated by Django 3.2.12 on 2022-02-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes_app', '0015_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
